config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :questionnaires
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :questionnaire
  has_many :answers, dependent: :destroy
  accepts_nested_attributes_for :answers, allow_destroy: true

  enum question_type: { single_choice: 0, multiple_choice: 1, long_answer: 2 }

  def self.question_type_select
    question_types.keys.map { |k| [k.titleize, k] }
  end
end

app/models/questionnaire.rb
class Questionnaire < ApplicationRecord
  has_many :questions, dependent: :destroy
  accepts_nested_attributes_for :questions, allow_destroy: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:teacher_role, :student_role, :name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:teacher_role, :student_role, :name])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]
  before_action :check_signed_in

  def check_signed_in
    redirect_to questionnaires_path if signed_in?
  end

  def home
  end
end

app/controllers/questionnaires_controller.rb
class QuestionnairesController < ApplicationController
  before_action :set_questionnaire, only: %i[ show edit update destroy ]

  def index
    @questionnaires = Questionnaire.all
    user = current_user
    @quest_user = Questionnaire.where(user: user)
  end

  def show
  end

  def new
    @questionnaire = Questionnaire.new
  end

  def edit
  end

  def create
    @questionnaire = Questionnaire.new(questionnaire_params)
    @questionnaire.user = current_user

    respond_to do |format|
      if @questionnaire.save
        format.html { redirect_to questionnaire_url(@questionnaire), notice: "Questionnaire was successfully created." }
        format.json { render :show, status: :created, location: @questionnaire }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @questionnaire.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @questionnaire.update(questionnaire_params)
        format.html { redirect_to questionnaire_url(@questionnaire), notice: "Questionnaire was successfully updated." }
        format.json { render :show, status: :ok, location: @questionnaire }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @questionnaire.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @questionnaire.destroy

    respond_to do |format|
      format.html { redirect_to questionnaires_url, notice: "Questionnaire was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_questionnaire
    @questionnaire = Questionnaire.find(params[:id])
  end

  def questionnaire_params
    params.require(:questionnaire).permit(
      :name,
      questions_attributes: [
          :destroy,
          :id,
          :question_type,
          :name,
          answers_attributes: [:_destroy, :id, :name, :correct]
      ]
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Smart Tests</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%#= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" id="mysite" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/ddxlnxcu5/image/upload/v1653482325/production/wp2151561-bookshelf-wallpapers_pvergg.jpg)">
  <div class="container">
    <%= image_tag 'logo.png', class: "img-fluid" %>

    <div class="btn-container">
     <% if user_signed_in? %>
        <p class="botao-home"><%= link_to 'I\'m a teacher', questionnaires_path %></p>
        <p class="botao-home"><%= link_to 'I\'m a student', questionnaires_path %></p>
       <% else %>
          <p class="botao-home"><%= link_to 'I\'m a teacher', new_user_session_path %></p>
          <p class="botao-home"><%= link_to 'I\'m a student', new_user_session_path %></p>
          </li>
        <% end %>
    </div>
  </div>
</div>

app/views/questionnaires/_answer_fields.html.erb
<div class='nested-fields'>
  <div class='form-group mb-2'>
    <%= form.hidden_field :_destroy %>
    <%= form.text_field :name, placeholder: 'Answer', class: 'form-control' %> 
    <%= form.check_box :correct %>  Correct answer
    <small>
      <%= link_to "Remove Answer", "#", data: { action: "click->nested-form#remove_association" } %>
    </small>
  </div>
<div>

app/views/questionnaires/_form.html.erb
<div class="container">
<div class="row mt-3 mb-5">
<%= form_with(model: questionnaire) do |form| %>

  <div class="field mb-2">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div data-controller="nested-form">
    <template data-nested-form-target='template'>
      <%= form.fields_for :questions, Question.new, child_index: 'TEMPLATE_RECORD' do |question| %>
        <%= render 'question_fields', form: question %>
      <% end %>
    </template>

    <%= form.fields_for :questions do |question| %>
      <%= render 'question_fields', form: question %>
    <% end %>

    <div data-nested-form-target="add_item">
      <%= link_to "Add question", "#", data: { action: "nested-form#add_association" }, class: "btn btn-secondary ms-4"  %>
    </div>
  </div>

    <div class="actions mt-2 ms-4">
      <%= form.submit %>
    </div>
  <% end %>
</div>
</div>

app/views/questionnaires/_question_fields.html.erb
<div class='nested-fields box' data-controller='dynamic-select'>
  <div class='form-group mb-3'>
    <%= form.select :question_type,
        options_for_select(Question.question_type_select, selected: form.object.question_type),
        {},
        'data-dynamic-select-target': 'select',
        'data-action': 'dynamic-select#selected' %>
  </div>

  <div class='form-group'>
    <%= form.hidden_field :_destroy %>
    <%= form.text_field :name, placeholder: 'Question', class: 'form-control' %>
    <small>
      <%= link_to "Remove question", "#", data: { action: "click->nested-form#remove_association" } %>
    </small>
  </div>

    <div data-controller="nested-form" data-dynamic-select-target='choice'>
    <template data-nested-form-target='template'>
      <%= form.fields_for :answers, Answer.new, child_index: 'TEMPLATE_RECORD' do |answer| %>
        <%= render 'answer_fields', form: answer %>
      <% end %>
    </template>

    <%= form.fields_for :answers do |answer| %>
      <%= render 'answer_fields', form: answer %>
    <% end %>

    <div data-nested-form-target="add_item">
      <%= link_to "Add answer", "#", data: { action: "nested-form#add_association" }, class: "btn btn-primary mt-2 mb-2 ms-4" %>
    </div>
  </div>

  <div data-controller="nested-form" data-dynamic-select-target='long'>
  </div>
</div>

app/views/questionnaires/edit.html.erb
<div class="container">
<div class="row mt-3 mb-5">

<h1>Editing Questionnaire</h1>
</div>
<%= render 'form', questionnaire: @questionnaire %>

<%= link_to 'Show', @questionnaire, class: "btn btn-outline-primary mt-3" %>
<%= link_to 'Back', questionnaires_path, class: "btn btn-outline-secondary mt-3" %>
<div>

app/views/questionnaires/index.html.erb
<%= render 'shared/navbar' %>
<% if current_user.teacher_role? %>
<div class="container">
<div class="row mt-3 mb-5">
  <div class="col-md-3">

<p><h1>Assessments</h1></p>

<%= link_to 'Add a new one', new_questionnaire_path, class: "btn btn-primary" %>

<table class="mt-3">
  <thead>
    <tr>
      <th>Subject</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quest_user.each do |questionnaire| %>
      <tr>
        <td><%= questionnaire.name %></td>
        <td><%= link_to 'Show', questionnaire, class: "btn btn-secondary" %></td>
        <td><%= link_to 'Edit', edit_questionnaire_path(questionnaire), class: "btn btn-secondary" %></td>
        <td><%= link_to 'Destroy', questionnaire, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-secondary" %></td>
      </tr>
    <% end %>
   </tbody>
</table>
<br>
</div>
</div>
</div>
<% else %>
          <h2> STUDENT <h2>
          <div class="container">
      <h1>Welcome to your dashboard <%= current_user.name %>!</h1>
      <div class="start_btn"><button>Start Quiz</button></div>

    <!-- Info Box -->
    <div class="info_box">
        <div class="info-title"><span>Some Rules of this Quiz</span></div>
        <div class="info-list">
            <div class="info">1. You will have only <span>15 seconds</span> per each question.</div>
            <div class="info">2. Once you select your answer, it can't be undone.</div>
            <div class="info">3. You can't select any option once time goes off.</div>
            <div class="info">4. You can't exit from the Quiz while you're playing.</div>
            <div class="info">5. You'll get points on the basis of your correct answers.</div>
        </div>
        <div class="buttons">
            <button class="quit">Exit Quiz</button>
            <button class="restart">Continue</button>
        </div>
    </div>

    <!-- Quiz Box -->
    <div class="quiz_box">
        <header>
            <div class="title">Start now!</div>
            <div class="timer">
                <div class="time_left_txt">Time Left</div>
                <div class="timer_sec">15</div>
            </div>
            <div class="time_line"></div>
        </header>
        <section>
            <div class="que_text">
                <!-- Here I've inserted question from JavaScript -->
                <%= javascript_pack_tag 'application' %>
            </div>
            <div class="option_list">
                <!-- Here I've inserted options from JavaScript -->
            </div>
        </section>

        <!-- footer of Quiz Box -->
        <footer>
            <div class="total_que">
                <!-- Here I've inserted Question Count Number from JavaScript -->
            </div>
            <button class="next_btn">Next Que</button>
        </footer>
    </div>

    <!-- Result Box -->
    <div class="result_box">
        <div class="icon">
            <i class="fas fa-crown"></i>
        </div>
        <div class="complete_text">You've completed the Quiz!</div>
        <div class="score_text">
            <!-- Here I've inserted Score Result from JavaScript -->
        </div>
        <div class="buttons">
            <button class="restart">Replay Quiz</button>
            <button class="quit">Quit Quiz</button>
        </div>
    </div>
<% end %>
<button class=coffee>
            <a href="https://open.spotify.com/playlist/7nCRh8ivvFmxhVqpD6PqM0?si=08f214d682d24cc3">
                  <div>
                    <span>
                      <p><i class="fa fa-mug-hot"></i> Need a coffee break?</p><p>:)</p>
                    </span>
                  </div>
                  <div>
                    <span>
                      <h4><i class="fab fa-spotify"></i> Listen our playlist on Spotify</h4>
                    </span>
                  </div>
              </a>
          </button>
</div>

app/views/questionnaires/new.html.erb
<div class="container">
<div class="row mt-3 mb-5">
  <div class="col-md-5">
<h1>New Assessment</h1>

<%= render 'form', questionnaire: @questionnaire, class: "ml-6" %>
<%= link_to 'Back', questionnaires_path, class: "btn btn-outline-secondary mt-1" %>
</div>
</div>
</div>

app/views/questionnaires/show.html.erb
<div class="row justify-content-center mt-4 mb-5">
  <div class="col-md-3">

  <h3 class="mb-4"><%= @questionnaire.name %></h3>

  <% @questionnaire.questions.each do |question| %>
    <h4><%= question.name %></h4>

    <% case question.question_type %>
      <% when 'single_choice' %>
        <% question.answers.each do |answer| %>
          <p>
            <%= radio_button_tag question.id, answer.id %>
            <%= answer.name %>
          </p>
        <% end %>
      <% when 'multiple_choice' %>
        <% question.answers.each do |answer| %>
          <p>
            <%= check_box_tag question.id, answer.id %>
            <%= answer.name %>
          </p>
        <% end %>
      <% when 'long_answer' %>
        <%= text_area_tag question.id %>
    <% end %>
  <% end %>

<%= link_to 'Edit', edit_questionnaire_path(@questionnaire), class: "btn btn-outline-primary mt-4" %>
<%= link_to 'Back', questionnaires_path, class: "btn btn-outline-secondary mt-2" %>
</div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "logo_navbar_azul.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? && current_user.teacher_role? %>
          <li class="nav-item active">
            <%= link_to "Home", "http://localhost:3000/", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to " Create one", "http://localhost:3000/questionnaires/new", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "logo_navbar_azul.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%#= link_to "Action", "#", class: "dropdown-item" %>
              <%#= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
          <% elsif user_signed_in? && current_user.teacher_role == false%>
          <li class="nav-item active">
            <%= link_to "Home", "http://localhost:3000/", class: "nav-link" %>
          <% else%>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>